FIX don't try to test non existent files
Previously there was a _config.php file that we would run phpcs over in
the Travis CI tool. However this file was recently removed, so now the
build fails with:
ERROR: The file "*.php" does not exist.
So lets stop looking for/trying to sniff/clean it :)